[features]
seeds = false
[programs.devnet]
felicias_crypto_fruitstand = "Aru5TV39J4P7Fx75BhhPieTKbsJLR4917HysPeo6d5TA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/threedevx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
